### ISSUE TITLE
Support for random named images

### ISSUE THREAD

**Issue by jslattery26** [aliyigitbireroglu/flutter-image-sequence-animator#6]
I love this package, its exactly what I need. But I have images in firebase storage where the names are generated and don't follow the naming format you have implemented. Is there a possibility for an implementation where the frames can be looped from a list of urls instead?

**Comment by aliyigitbireroglu** [comment]
Yes I believe that can be done easily. I will need to make a few changes and I will notify you when possible.

**Comment by aliyigitbireroglu** [comment]
Alright, I updated the package both on pub.dev and GitHub. Now you can pass an array of URLs or local paths to the widget which will be used instead of the [folderName], [fileName], [suffixStart], [suffixCount], [fileFormat] and [frameCount] values. See the example project if you need help and feel free to ask more.

**Comment by jslattery26** [comment]
Appreciate it man! Thanks
